INSERT INTO treatments (treatment_code, treatment_description, treatment_rate) VALUES ('C11', 'Periodieke controle', 22.91);
INSERT INTO treatments (treatment_code, treatment_description, treatment_rate) VALUES ('C13', 'Probleemgericht consult', 22.91);
INSERT INTO treatments (treatment_code, treatment_description, treatment_rate) VALUES ('C91', 'Pocketregistratie', 36.18);
INSERT INTO treatments (treatment_code, treatment_description, treatment_rate) VALUES ('C92', 'Parodontiumregistratie', 72.35);
INSERT INTO treatments (treatment_code, treatment_description, treatment_rate) VALUES ('C22', 'Aanvullende medische anamnese na (schriftelijke) routinevragen', 22.91);
INSERT INTO treatments (treatment_code, treatment_description, treatment_rate) VALUES ('C28', 'Uitgebreid onderzoek t.b.v. opstellen. vastleggen en verstrekken van behandelplan aan de patiënt', 108.53);
INSERT INTO treatments (treatment_code, treatment_description, treatment_rate) VALUES ('C29', 'Studiemodellen t.b.v. behandelplan', 30.15);
INSERT INTO treatments (treatment_code, treatment_description, treatment_rate) VALUES ('C65', 'Planmatig beslijpen van alle voortanden. per boven- of onderkaak', 60.29);
INSERT INTO treatments (treatment_code, treatment_description, treatment_rate) VALUES ('X10', 'Maken en beoordelen kleine röntgenfoto', 16.88);
INSERT INTO treatments (treatment_code, treatment_description, treatment_rate) VALUES ('X11', 'Beoordelen kleine röntgenfoto', 12.66);
INSERT INTO treatments (treatment_code, treatment_description, treatment_rate) VALUES ('X21', 'Maken en beoordelen kaakoverzichtsfoto', 72.35);
INSERT INTO treatments (treatment_code, treatment_description, treatment_rate) VALUES ('X22', 'Maken en beoordelen kaakoverzichtsfoto t.b.v. implantologie in de tandeloze kaak', 72.35);
INSERT INTO treatments (treatment_code, treatment_description, treatment_rate) VALUES ('X23', 'Beoordelen kaakoverzichtsfoto', 26.53);
INSERT INTO treatments (treatment_code, treatment_description, treatment_rate) VALUES ('X24', 'Maken en beoordelen schedelfoto', 32.56);
INSERT INTO treatments (treatment_code, treatment_description, treatment_rate) VALUES ('X34', 'Beoordelen schedelfoto', 24.12);
INSERT INTO treatments (treatment_code, treatment_description, treatment_rate) VALUES ('X25', 'Maken en beoordelen meerdimensionale kaakfoto', 204.99);
INSERT INTO treatments (treatment_code, treatment_description, treatment_rate) VALUES ('X26', 'Beoordelen meerdimensionale kaakfoto', 60.29);
INSERT INTO treatments (treatment_code, treatment_description, treatment_rate) VALUES ('M01', 'Preventieve voorlichting en/of instructie. per vijf minuten', 13.52);
INSERT INTO treatments (treatment_code, treatment_description, treatment_rate) VALUES ('M02', 'Consult voor evaluatie van preventie. per vijf minuten', 13.52);
INSERT INTO treatments (treatment_code, treatment_description, treatment_rate) VALUES ('M03', 'Gebitsreiniging. per vijf minuten', 13.52);
INSERT INTO treatments (treatment_code, treatment_description, treatment_rate) VALUES ('M05', 'Niet-restauratieve behandeling van cariës in het melkgebit', 27.13);
INSERT INTO treatments (treatment_code, treatment_description, treatment_rate) VALUES ('M32', 'Eenvoudig bacteriologisch- of enzymatisch onderzoek', 18.09);
INSERT INTO treatments (treatment_code, treatment_description, treatment_rate) VALUES ('M30', 'Behandeling van gevoelige tandhalzen en (preventief) toedienen medicament', 6.03);
INSERT INTO treatments (treatment_code, treatment_description, treatment_rate) VALUES ('M40', 'Fluoridebehandeling', 15.07);
INSERT INTO treatments (treatment_code, treatment_description, treatment_rate) VALUES ('M61', 'Mondbeschermer', 27.13);
INSERT INTO treatments (treatment_code, treatment_description, treatment_rate) VALUES ('M80', 'Behandeling van witte vlekken. eerste element', 52.45);
INSERT INTO treatments (treatment_code, treatment_description, treatment_rate) VALUES ('M81', 'Behandeling van witte vlekken. volgend element', 28.94);
INSERT INTO treatments (treatment_code, treatment_description, treatment_rate) VALUES ('A15', 'Oppervlakte verdoving', 7.84);
INSERT INTO treatments (treatment_code, treatment_description, treatment_rate) VALUES ('A10', 'Geleidings-. infiltratie- en/of intraligamentaire verdoving', 15.07);
INSERT INTO treatments (treatment_code, treatment_description, treatment_rate) VALUES ('B10', 'Introductie roesje (lachgassedatie)', 30.15);
INSERT INTO treatments (treatment_code, treatment_description, treatment_rate) VALUES ('B11', 'Toediening roesje (lachgassedatie)', 30.15);
INSERT INTO treatments (treatment_code, treatment_description, treatment_rate) VALUES ('B12', 'Overheadkosten roesje (lachgassedatie)', 37.38);
INSERT INTO treatments (treatment_code, treatment_description, treatment_rate) VALUES ('V71', 'Eénvlaksvulling amalgaam', 25.32);
INSERT INTO treatments (treatment_code, treatment_description, treatment_rate) VALUES ('V72', 'Tweevlaksvulling amalgaam', 40.4);
INSERT INTO treatments (treatment_code, treatment_description, treatment_rate) VALUES ('V73', 'Drievlaksvulling amalgaam', 52.45);
INSERT INTO treatments (treatment_code, treatment_description, treatment_rate) VALUES ('V74', 'Meervlaksvulling amalgaam', 73.56);
INSERT INTO treatments (treatment_code, treatment_description, treatment_rate) VALUES ('H11', 'Trekken tand of kies', 45.22);
INSERT INTO treatments (treatment_code, treatment_description, treatment_rate) VALUES ('H16', 'Trekken volgende tand of kies. in dezelfde zitting en hetzelfde kwadrant', 33.76);
INSERT INTO treatments (treatment_code, treatment_description, treatment_rate) VALUES ('H21', 'Kosten hechtmateriaal', 6.18);
INSERT INTO treatments (treatment_code, treatment_description, treatment_rate) VALUES ('H26', 'Hechten weke delen', 66.32);
INSERT INTO treatments (treatment_code, treatment_description, treatment_rate) VALUES ('H50', 'Terugzetten/ terugplaatsen tand of kies. eerste element exclusief wortelkanaalbehandeling', 60.29);
INSERT INTO treatments (treatment_code, treatment_description, treatment_rate) VALUES ('H90', 'Voorbereiding praktijkruimte ten behoeve van chirurgische verrichtingen vallend onder onderdeel B', 60.29);
INSERT INTO treatments (treatment_code, treatment_description, treatment_rate) VALUES ('H33', 'Hemisectie van een molaar', 72.35);
INSERT INTO treatments (treatment_code, treatment_description, treatment_rate) VALUES ('H35', 'Moeizaam trekken tand of kies. met mucoperiostale opklap', 72.35);

INSERT INTO appointments (id, name_dentist, surname_dentist, appointment_date_time) VALUES (1001, 'Piet', 'Janssen', '2023-03-15T14:30');
INSERT INTO appointments (id, name_dentist, surname_dentist, appointment_date_time) VALUES (1002, 'Piet', 'Janssen', '2023-03-15T13:30');
INSERT INTO appointments (id, name_dentist, surname_dentist, appointment_date_time) VALUES (1003, 'Piet', 'Janssen', '2023-03-15T15:30');
INSERT INTO appointments (id, name_dentist, surname_dentist, appointment_date_time) VALUES (1004, 'Piet', 'Janssen', '2023-03-15T15:45');
INSERT INTO appointments (id, name_dentist, surname_dentist, appointment_date_time) VALUES (1005, 'Piet', 'Janssen', '2023-03-15T16:00');
INSERT INTO appointments (id, name_dentist, surname_dentist, appointment_date_time) VALUES (1006, 'Piet', 'Janssen', '2023-03-16T08:00');
INSERT INTO appointments (id, name_dentist, surname_dentist, appointment_date_time) VALUES (1007, 'Annette', 'Huis', '2023-03-15T08:00');
INSERT INTO appointments (id, name_dentist, surname_dentist, appointment_date_time) VALUES (1008, 'Annette', 'Huis', '2023-03-15T08:30');
INSERT INTO appointments (id, name_dentist, surname_dentist, appointment_date_time) VALUES (1009, 'Annette', 'Huis', '2023-03-15T09:45');
INSERT INTO appointments (id, name_dentist, surname_dentist, appointment_date_time) VALUES (1010, 'Annette', 'Huis', '2023-03-15T10:30');
INSERT INTO appointments (id, name_dentist, surname_dentist, appointment_date_time) VALUES (1011, 'Annette', 'Huis', '2023-03-15T11:30');
INSERT INTO appointments (id, name_dentist, surname_dentist, appointment_date_time) VALUES (1012, 'Annette', 'Huis', '2023-03-17T15:30');
INSERT INTO appointments (id, name_dentist, surname_dentist, appointment_date_time) VALUES (1013, 'Femke', 'Mittelberg', '2023-03-15T11:00');
INSERT INTO appointments (id, name_dentist, surname_dentist, appointment_date_time) VALUES (1014, 'Femke', 'Mittelberg', '2023-03-15T13:30');
INSERT INTO appointments (id, name_dentist, surname_dentist, appointment_date_time) VALUES (1015, 'Femke', 'Mittelberg', '2023-03-15T15:30');
INSERT INTO appointments (id, name_dentist, surname_dentist, appointment_date_time) VALUES (1016, 'Femke', 'Mittelberg', '2023-03-18T09:30');
INSERT INTO appointments (id, name_dentist, surname_dentist, appointment_date_time) VALUES (1017, 'Femke', 'Mittelberg', '2023-03-15T11:30');
INSERT INTO appointments (id, name_dentist, surname_dentist, appointment_date_time) VALUES (1018, 'Femke', 'Mittelberg', '2023-03-15T15:15');

